### PR TITLE
151 afegir amic web

### PR DESCRIPTION
**Pull request by Alfons0Cano**
add: add friend button, pending friend request list

### CODE REVIEW

**Review by Ericriera — CHANGES_REQUESTED** [review]
Solve conflicts

**Review by Ericriera — CHANGES_REQUESTED** [review]
Delete cosole.log & fix item list(see assistants, admin/users & ranking not working,  appearing add friend icon in admin/events when event is created by us)

**Comment by Alfons0Cano** [comment]
Can Send Request:
image
Friend request sent:
image
Friend request recieved:
image
Already Friend:
image
Add Friend button on assistant list:
image

**Comment by Alfons0Cano** [comment]
Modified: position of addFriend on user view:
image

**Review by Ericriera — CHANGES_REQUESTED** [review]
Puedes aceptar o rechazar solicitudes de otros usuarios desde su lista de amigos, y no se debería poder

**Review by Ericriera — APPROVED** [review]
Ready to merge

**Pull request merged**
